### ISSUE TITLE
Use Uint32Array when necessary

### ISSUE THREAD

**Issue by vorg** [vorg/geom-builder#4]
It is possible to build mesh with more than 64k vertices that creates clamped indices due to Uint16Array array for cell. Either we should switch to Uint32Array or upgrade to it once positionsIndex is above 60k

**Comment by vorg** [comment]
Another option would be to specify type, constructor or provide initial indices array in anticipation of big vertex count.

```js
createGeomBuilder({ positions: 3, colors: 4, cells: { size: 3, type: Uint32Array } })
```

**Comment by dmnsgn** [comment]
> Another option would be to specify type, constructor or provide initial indices array in anticipation of big vertex count.
> 
> ```js
> createGeomBuilder({ positions: 3, colors: 4, cells: { size: 3, type: Uint32Array } })
> ```

I have my [typed-array-constructor](https://github.com/dmnsgn/typed-array-constructor) for that purpose.

**Comment by vorg** [comment]
Wanna patch it here?

**Comment by vorg** [comment]
And if we will use it i suggest a bit more readable syntax

```js
new (typedArrayConstructor(indexCount * 2))(10); //anticipating next resize
```
vs
```js
const DetectedArrayType = typedArrayConstructor(indexCount * 2) //anticipating next resize
indicesArray = new DetectedArrayType(10);
```
